name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Add Target
      run: rustup target add aarch64-unknown-linux-gnu
    - name: Install Nightly Toolchain
      run: rustup toolchain install nightly
    - name: Switch to Nightly Channel
      run: rustup default nightly
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
