name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [aarch64-unknown-linux-gnu]

    steps:
    - uses: actions/checkout@v3
    - name: Install rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        profile: minimal
        override: true
        target: ${{ matrix.target }}
    - name: Build
      run: cargo build --target ${{ matrix.target }} --verbose
    - name: Run tests
      run: cargo test --verbose
